// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArCpSiEygM7VUaPVsIzJ4LrkbGrZ5Jo7w',
    appId: '1:332763393531:web:52914283011a39022baf5e',
    messagingSenderId: '332763393531',
    projectId: 'mis-lab4-2df46',
    authDomain: 'mis-lab4-2df46.firebaseapp.com',
    storageBucket: 'mis-lab4-2df46.appspot.com',
    measurementId: 'G-J1BMH90QLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt34l0JEfeV_-AGmkulpKH9J6lnvNbW58',
    appId: '1:332763393531:android:b3d7aa09a6fd1bc42baf5e',
    messagingSenderId: '332763393531',
    projectId: 'mis-lab4-2df46',
    storageBucket: 'mis-lab4-2df46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp22q1Qf38EQEsgsuHzqSbFsK8naxvUAg',
    appId: '1:332763393531:ios:4c1f422327bab05a2baf5e',
    messagingSenderId: '332763393531',
    projectId: 'mis-lab4-2df46',
    storageBucket: 'mis-lab4-2df46.appspot.com',
    iosClientId: '332763393531-se9f9eco45d0262q8vg1nq74c2uep91l.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp22q1Qf38EQEsgsuHzqSbFsK8naxvUAg',
    appId: '1:332763393531:ios:4c1f422327bab05a2baf5e',
    messagingSenderId: '332763393531',
    projectId: 'mis-lab4-2df46',
    storageBucket: 'mis-lab4-2df46.appspot.com',
    iosClientId: '332763393531-se9f9eco45d0262q8vg1nq74c2uep91l.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab3',
  );
}
